name: rsa_identification
description: A Dart Library for decoding and providing South African identification details from documents such as Driver's licenses and Smart ID's.
version: 1.0.3
homepage: https://github.com/born-ideas/rsa_identification

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  asn1lib: ^0.8.1
  meta: ^1.2.3

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
