name: rsa_identification
description: A Dart Library for decoding and providing South African identification details from documents such as Driver's licenses and Smart ID's.
version: 0.0.1+1
homepage: https://github.com/marcus-bornman/rsa_identification

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  asn1lib: ^0.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
